// Auto-generated wake word model parameters
#ifndef WAKEWORD_MODEL_H
#define WAKEWORD_MODEL_H

#define WAKEWORD_INPUT_FEATURES 13
#define WAKEWORD_HIDDEN_SIZE 24
#define WAKEWORD_NUM_LAYERS 3
#define WAKEWORD_WINDOW_SIZE_MS 500
#define WAKEWORD_HOP_LENGTH_MS 100
#define WAKEWORD_SAMPLE_RATE 16000

#define WAKEWORD_FFT_SIZE 512
#define WAKEWORD_MEL_BANDS 40

#define WAKEWORD_DETECTION_THRESHOLD 0.7f

#endif // WAKEWORD_MODEL_H
